/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tensorflow_demo_TensorflowClassifier */

#ifndef _Included_org_tensorflow_demo_TensorflowClassifier
#define _Included_org_tensorflow_demo_TensorflowClassifier
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tensorflow_demo_TensorflowClassifier
 * Method:    classifyImageRgb
 * Signature: ([III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_tensorflow_demo_TensorflowClassifier_classifyImageRgb
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     org_tensorflow_demo_TensorflowClassifier
 * Method:    classifyActivityAccRaw
 * Signature: (I[F)I
 */
JNIEXPORT jint JNICALL Java_org_tensorflow_demo_TensorflowClassifier_classifyActivityAccRaw
  (JNIEnv *, jobject, jint, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
